### ISSUE TITLE
Error on startup (Linux)

### ISSUE THREAD

**Issue by erkam2002** [iPocketTeam/Minecraft-Client#1]
[MainLogger][INFO] MinecraftClient starting now...
ErrorLog: socket_connect(): unable to connect [111]: Connection refused : /root/Minecraft-Client-master/src/MinecraftClient/utils/SocketReader.php : 28
1: SocketReader.php: socket_connect
2: MinecraftClient.php: __construct
3: start.php: __construct
[MainLogger][INFO] SocketError
[MainLogger][INFO] Shutdown a system now...
[MainLogger][INFO] Thank you for using MinecraftClient by iPocket!

**Comment by hmy2001** [comment]
Please start up the server first and then start up

**Comment by erkam2002** [comment]
Server?

**Comment by hmy2001** [comment]
Yes, Minecraft Server.

**Comment by erkam2002** [comment]
Oh ok
